site:
  title: "hiroto's things"
  author: rodigu
  email: rmoraisu@proton.me
  url: https://rodigu.github.io
  description: "personal website with technical writing, tiny game demos, and photo-logs"
  theme_color: '#5670d4'
  font: 'Share+Tech+Mono'
  variant: dark
  footer: "Contents © {year} <a href=\"mailto:{email}\">{author}</a>"

nav:
  - url: categories/cat_reading/
    label: reading
  - url: categories/cat_music/
    label: music
  - url: categories/cat_linux/
    label: linux
  - url: categories/cat_data-eng/
    label: data
  - url: rss.xml
    label: rss
  - url: pages/about/index.html
    label: about

output: docs

image_folders:
  images: posts/images

comments:
  system: utterances
  repo: rodigu/rodigu.github.io
